### ISSUE TITLE
-q option needed for some versions of octave

### ISSUE THREAD

**Issue by magland** [jamesjun/ironclust#1]
Please put the -q flag in the octave call in the ml_ironclust.mp file.

**Comment by jamesjun** [comment]
How about doing this to remove dependency to octave?

matlab -nodisplay -r "ml_ironclust_spec"


-James

**Comment by magland** [comment]
we can try it.

**Comment by jamesjun** [comment]
octave -q flag is added. Matlab is not used since it displays splash screen and it could not be disabled by using "-nosplash" switch.
