### ISSUE TITLE
Splitting Spikes in PSTH

### ISSUE THREAD

**Issue by zsperry** [jamesjun/ironclust#12]
Would it be possible to implement a manual splitter in the PSTH window? Here's a sample of what I'd like to be able to do:

![image](https://user-images.githubusercontent.com/22245639/52494637-7f2c1a00-2b9c-11e9-8e41-ac6f9de5470f.png)

**Comment by jamesjun** [comment]
good idea Zach.  There might be a waveform difference. I will build a GUI tool for that. 

-James

**Comment by zsperry** [comment]
A thought: the tool might be best if it allowed separation of a time interval, as opposed to the polygon separation that is in the splitting GUI. Could even be a textbox tool instead of a graphical one. But whatever is simplest for you.

**Comment by jamesjun** [comment]
Okay. One idea is that a user can right-click on the PSTH window to draw
either horizontal (time separation) or vertical line (trial separation) and
split a cluster.

-James

**Comment by zsperry** [comment]
I like it. In my current dataset I have utility for both
