### ISSUE TITLE
URGENT: Cluster amplitude incorrectly reported

### ISSUE THREAD

**Issue by zsperry** [jamesjun/ironclust#14]
Clusters that based on the Time v. Amplitude graph are very large (~70uVpp) have calculated amplitude much smaller (8.7uVpp) in the unit position graph and when the values are exported. Makes it hard to trust any of the values. See snippet, cluster 84 is a good example of this. I'll send you the files.
![manual_gui](https://user-images.githubusercontent.com/22245639/54771986-cfa38800-4bdc-11e9-9098-8222d0084bb5.PNG)

**Comment by jamesjun** [comment]
Fixed.
