### ISSUE TITLE
Issue with Show averaged waveforms on all channels

### ISSUE THREAD

**Issue by zsperry** [jamesjun/ironclust#16]
When I run the command with fShow_raw=0, the filtering gives me an error. Here's the output: 
![image](https://user-images.githubusercontent.com/22245639/57309014-517c4180-70b5-11e9-846e-535304aa7705.png)

**Comment by jamesjun** [comment]
Thanks, the issue is fixed in v4.5.8. vcFilter='bandpass' caused error previously and now it works.
