### ISSUE TITLE
Problem running ironclust with spiketoolkit

### ISSUE THREAD

**Issue by samuelgarcia** [jamesjun/ironclust#18]
Hi @jamesjun : I am trying to make ironclust running with the spiketoolkit.sorters.IronclustSorter.

It trigger an error, is it easy to fix ?

```
nSites_use = maxSite*2+1 - nSites_ref must be greater than 0:
Index exceeds matrix dimensions.

Error in irc>tnWav2pv_ (line 7094)
    case 1, mrSpkWav1 = tr(:,viSpk_sub, 1);

Error in irc>trWav2fet_ (line 6985)
                    [mrPv_global, vrD_global] = tnWav2pv_(trWav2_spk, P);

Error in irc>wav2spk_ (line 15993)
        mrFet1 = trWav2fet_(tnWav_spk, P); fprintf('.');

Error in irc>file2spk_ (line 16457)
        [tnWav_raw_, tnWav_spk_, trFet_spk_, miSite_spk{end+1}, viTime_spk{end+1}, vrAmp_spk{end+1}, vnThresh_site{end+1}, P.fGpu] ...

Error in irc>detect_ (line 983)
        S0 = file2spk_(P, viTime_spk0, viSite_spk0);

Error in irc>run_irc_ (line 27918)
detect_(P); sort_(P, 0); describe_(P.vcFile_prm);

Error in irc>run_algorithm_ (line 27905)
    case 'ironclust', run_irc_(P);

Error in irc (line 200)
        run_algorithm_(P);

Error in p_ironclust (line 10)
irc('run', vcFile_prm);
```

**Comment by jamesjun** [comment]
Thanks. I will take a look on Tuesday after returning from a trip. In the mean time you may wish to take a look at the IronClust wrapper I wrote for SpikeForest/SpikeSorters/IronClust wrapper on github.

We added an automated install script for the IronClust class and other Matlab classes which inherits a MLPR.Processor parent class. 

-James

**Comment by samuelgarcia** [comment]
Thank you.
I will have a look.
Apart installation script and container, Is there big difference between  wrapper in SF and ST ?

**Comment by jamesjun** [comment]
I don't think so. Jeremy and Alessio made two IronClust wrappers such that the SpikeForest wrapper calls the SpikeToolkit wrapper. SpikeForest wrapper handles the installation and its parent class handles batch processing through Slurm. SpikeToolkit wrapper handles the rest.

**Comment by samuelgarcia** [comment]
Hi James,
Thank.
I know.
Now all wrapper are in spikesorter so there is only one wrapper for each sorter.
And now ironclust is also  working in ST so.
Best
