### ISSUE TITLE
Note: Old files now making errors

### ISSUE THREAD

**Issue by zsperry** [jamesjun/ironclust#20]
I know you said you were letting go of some backward compatibility stuff, but just fyi my older prm files now throw an error at nanmean_int_16_. If there's a way to restore compatibility, that would be awesome, but otherwise I'll just continue working from the 6/17/19 version that still works and still has the features I need (driftview in particular).

Error details:

```
Index exceeds matrix dimensions.

Error in irc>nanmean_int16_ (line 10202)
        trWav(:, viSite1a_, viSpk_) = tnWav0(:,viSite1b_,viSpk_); % P.miSites(:,iSite_unique)

Error in irc>clu_wav_ (line 10146)
    mrWav_lo_clu1 = nanmean_int16_(tnWav_(:,:,viSpk_clu_), 3, fUseCenterSpk, iSite_clu1,
    viSite_clu_, S0.P);

Error in irc>S_clu_wav_ (line 10048)
            [mrWav_clu1, viSite_clu1, mrWav_lo_clu1, mrWav_hi_clu1] = clu_wav_(S_clu, tnWav_,
            iClu, S0);

Error in irc>S_clu_update_wav_ (line 4586)
S_clu = S_clu_wav_(S_clu, [], [], S0);

Error in irc>manual_ (line 5586)
                    S0.S_clu = S_clu_update_wav_(S0.S_clu, P);

Error in irc (line 277)
    manual_(P);
```

**Comment by jamesjun** [comment]
Sorry about that Zach, I changed the internal representation of spike waveforms from int16 to single precision format. The change improved the sorting accuracy while increasing the memory use by 25%. I didn’t check for the backward compatibility. I will make it backward compatible. 

-James

**Comment by jamesjun** [comment]
resolved in v4.9.1

**Comment by zsperry** [comment]
Hmm...still a problem for me...

**Comment by jamesjun** [comment]
Sorry, let me find one of the older files you shared with me and test on
that.

-James
