### ISSUE TITLE
Out of memory issues when trying to export to "Klusters/neurosuite" format for long recordings

### ISSUE THREAD

**Issue by bapungiri** [jamesjun/ironclust#21]
I am getting the following error when trying to export the files into neurosuite format. This error was not encountered for sample data but happens for long recordings (>14 hrs).
Other details:
ironclust version 4.8.10

>> irc export-klusters Shank3-4.prm
loading Shank3-4_jrc.mat...
	took 1.5s
Computing templates per unit
	> In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>disperr_ (line 18291)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>fread_ (line 5346)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>load_bin_ (line 2247)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>load_bin_T_ (line 30524)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>load_wav_med_ (line 30555)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>test_ (line 19032)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>call_ (line 19066)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>irc (line 131)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc2klusters.m>irc2klusters (line 40)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>irc (line 178)
Error log updated: /home/bapung/Documents/MATLAB/ironclust/matlab/error_log.mat
Error using fread
Out of memory. Type "help memory" for your options.
GPU device reset
> In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>disperr_ (line 18291)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>load_bin_ (line 2253)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>load_bin_T_ (line 30524)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>load_wav_med_ (line 30555)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>test_ (line 19032)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>call_ (line 19066)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>irc (line 131)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc2klusters.m>irc2klusters (line 40)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>irc (line 178)
Error log updated: /home/bapung/Documents/MATLAB/ironclust/matlab/error_log.mat
Output argument "mnWav1" (and maybe others) not assigned during call to "irc>fread_".
GPU device reset
> In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>disperr_ (line 18291)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>test_ (line 19048)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>call_ (line 19066)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>irc (line 131)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc2klusters.m>irc2klusters (line 40)
  In /home/bapung/Documents/MATLAB/ironclust/matlab/irc.m>irc (line 178)
Error log updated: /home/bapung/Documents/MATLAB/ironclust/matlab/error_log.mat
Index in position 2 is invalid. Array indices must be positive integers or logical values.
GPU device reset
Output argument "varargout{2}" (and maybe others) not assigned during call to
"irc>call_".

Error in irc (line 131)
                case 2, [varargout{1}, varargout{2}] = call_(vcArg1, vcArg2);

Error in irc2klusters (line 40)
    [mrWav_clu1, mnWav_T] = irc('call','load_wav_med_', {P1, viTime_spk1, mnWav_T}); %
    not filtering

Error in irc (line 178)
    case {'export-klusters', 'klusters', 'neurosuite'}, irc2klusters(vcFile_prm,
    vcArg2);

**Comment by jamesjun** [comment]
I will work on a paged loading scheme to address this issue.

**Comment by jamesjun** [comment]
Resolved. I also implemented an exporter for phy. Usage: ‘irc export-klusters myparam.prm’. For phy, use ‘export-phy’ command.

**Comment by jamesjun** [comment]
Resolved. I also implemented an exporter for phy. Usage: ‘irc export-klusters myparam.prm’. For phy, use ‘export-phy’ command.
