### ISSUE TITLE
Can IronClust support A4x4-tet design?

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [jamesjun/ironclust#27]
A quick YES or NO question.

I don't find any *.prb file in the `prb` folder that matches the design below, but can this design be supported by manually editing a .prb file?

A4x4-tet-5mm-150-200-121

http://neuronexus.com/electrode-array/a4x4-tet-5mm-150-200-121/

**Comment by bapungiri** [comment]
Yes you can customize the .prb files according to your probe's electrode position.

**Comment by jamesjun** [comment]
Of course Kouichi, I will define each tetrode as its own shank such that each tetrode group gets processed separately.

For example, if chan 1,2,3,4 belong to tetrode 1 and chan 5,6,7,8 belong to tetrode 2, define

channels = [1,2,3,4,5,6,7,8].  % mapping between channel ID to site ID, sorted by the site ID (uses 1-base array indexing)
shank = [1,1,1,1,2,2,2,2]; % shank ID corresponding to each site
geometry = … % [nSites x 2 matrix, col1: x coordinates, col2: y coordinates

Please refer to the probe file from here:
https://github.com/JaneliaSciComp/JRCLUST/wiki/Probe-file <https://github.com/JaneliaSciComp/JRCLUST/wiki/Probe-file>

**Comment by kouichi-c-nakamura** [comment]
Thanks, guys! Because we're planning to order it, it's important to know if there is a tool that can handle it.

**Comment by jamesjun** [comment]
I think it might work well in Basal Ganglia.
I just added the probe file in the repository (a4x4nn.prb).
Here is the content of the probe file below. You may need to update the `channels` variable with the correct channel map from NeuroNexus.

% Order of the probe sites in the recording file
channels = 1:64; % assuming linear mapping between sites to channels. Refer to the NeuroNexus documentation for correct channel mapping.
 
% Site location in micrometers (x and y)
fh_col = @(x)x(:);
geometry = repmat([0, -17.6777, 17.6777, 0; 0, 17.6777, 17.6777, 35.3554]',[16,1]);
geometry(:,1) = geometry(:,1) + fh_col(repmat([0,200,400,600],[16,1]));
geometry(:,2) = geometry(:,2) + repmat(fh_col(repmat([0,150,300,450],[4,1])),[4,1]);
 
 
% Recording contact pad size in micrometers. Height x width
pad = [11 11];
 
% Shanks
shank = fh_col(repmat(1:16,[4,1]))';
 
% Micrometers per center-to-center vertical site spacing
um_per_pix = 17.6777;            

-----
> irc probe a4x4nn.prb % running this command will generate a plot below

**Comment by kouichi-c-nakamura** [comment]
Thanks a lot!
