### ISSUE TITLE
qqFactor definition

### ISSUE THREAD

**Issue by kouichi-c-nakamura** [jamesjun/ironclust#29]
Hi, 

In [`default.prm`](https://github.com/jamesjun/ironclust/blob/master/matlab/default.prm#L80), `qqFactor` is defined as

```matlab
qqFactor = 4.5 % Spike detection thresold (Threshold = qqFactor*S, S = med(x-med(x))/.6745). (RQ Quiroga'04).
```

Quiroga (2004) refers to [Donoho and Johnstone (1994)](https://academic.oup.com/biomet/article/81/3/425/256924) and that paper says:

> Our software estimates the noise level _sigma_ as the **median absolute deviation** of the wavelet coefficients at the finest level _J_, divided by 0.6745.

So, I'm wondering if the above description should be corrected as 

```matlab
Threshold = qqFactor*S, S = median(abs(x-median(x)))/0.6745
```
in other words, we may need `abs`, and also to make it MATLAB friendly use `median` instead of `med`?

**Comment by jamesjun** [comment]
The comment is fixed. In actuality, I perform

`Threshold = qqFactor*S, S = median(abs(x)) / 0.6745`
since `median(x)==0` after performing high-pass filtering operation (see line3242 in` irc.m`).
The median is estimated after subsampling the recording (100,000 samples) for each channel.

**Comment by kouichi-c-nakamura** [comment]
Thanks for the swift response!

**Comment by WeissShahaf** [comment]
@jamesjun 
is the threshold determined per data chunk?
because we're seeing firing rates differences that align perfectly to the chunk size
