### ISSUE TITLE
uimenu error

### ISSUE THREAD

**Issue by zsperry** [jamesjun/ironclust#3]
Some of the calls to uimenu in irc.m refer to a 'Text' property that should be a 'Label.' Fixed locally, but probably want to fix here too. Thanks for the updates!

-Zach

**Comment by jamesjun** [comment]
Thanks. What version of Matlab are you using? I should make it version neutral. 

-James

**Comment by zsperry** [comment]
2017a at the moment, though I just realized that...you had it as 'Label'
some places but not all...weird they would change that by version, but I
looked it up and you're right...

-Z

**Comment by jamesjun** [comment]
I wrote `uimenu_()` in irc.m which uses the appropriate field names depending on the Matlab version. `matlab_version_()` function returns the Matlab version installed on your system (2017.5 is returned if R2017b is installed and 2017 is returned if R2017 is installed).

**Comment by zsperry** [comment]
Thanks!
