### ISSUE TITLE
Smoothing Analog Signal

### ISSUE THREAD

**Issue by zsperry** [jamesjun/ironclust#5]
It would be really useful to be able to apply a smoothing operation to the analog signal. I implemented this in openNsx_ by adding this line: varargout{2} = smooth(double(S_nsx.Data),500);

But I'm sure there's a better way to do that, ideally in the dialog that adds the analog input? Thanks!

**Comment by zsperry** [comment]
Having this option for the firing rate would be helpful too, at least for correlation purposes.

**Comment by jamesjun** [comment]
Sure. I will implement it. Thanks for the great suggestion. 

-James

**Comment by jamesjun** [comment]
Smoothing analog signal is controlled by `nSmooth_aux_trial` parameter. Set it to 0 to disable it.
