### ISSUE TITLE
Stim Latency Tool

### ISSUE THREAD

**Issue by zsperry** [jamesjun/ironclust#6]
I know this one might take a bit longer, and I'm going to try to hack together a version myself in the meantime, but it would be great to have a tool to calculate latency from an event to cluster timing, something that would show a PSTH with a mean/median latency based on input times from the .nev (like  "Import Events" in the "Add Event Trial" though you could generalize it so other users can import different event time files). Should probably have options to control the PSTH (bin size/number, maximum time). It would also be cool to designate one of the units as a stimulation artifact, in case there's an issue with the .nev event timing. Let me know what you think...

**Comment by jamesjun** [comment]
PSTH tool already exists. Please take a look here:
https://github.com/JaneliaSciComp/JRCLUST/wiki/PSTH-view

It could improve though.

-James

**Comment by zsperry** [comment]
Fantastic, guess that's one we hadn't looked at together! I'll read up and
let you know if I have questions, glad I didn't dive in to making one :P

-Zach

**Comment by zsperry** [comment]
I added a few lines to the file extension case structure so this would read in events from .nev, same as i did for the Trials menu.

elseif matchFileExt_(vcFile_trial,'.nev')
        vcFile_nev = vcFile_trial;
        [~,hFile]=ns_OpenFile(vcFile_nev);
        vi_event = find(strcmp({hFile.Entity.EntityType}, 'Event'));
        [~, S_EntityInfo] = ns_GetEntityInfo(hFile, vi_event);
        vrTime_trial = zeros(S_EntityInfo.ItemCount, 1);
        for iT = 1:numel(vrTime_trial)
            [~, vrTime_trial(iT)]=ns_GetEventData(hFile, vi_event, iT);
        end

**Comment by zsperry** [comment]
Working with the new tool, and it loads the .nev file pretty well. I also like the new "settings" menu. But the PSTH I get looks very different than it used to...do I need to play with the settings? Here's a sample, let me know if you need more info. Currently using matlab 2017a.

![image](https://user-images.githubusercontent.com/22245639/50655428-24c8e980-0f5e-11e9-83ae-26becc207855.png)

**Comment by jamesjun** [comment]
Thanks for providing the details on the version number. Could you please tell me which .nev file you loaded ? I might have that file on my local drive to reproduce the error.

**Comment by jamesjun** [comment]
I believe this happens when there is only one trial in .nev file. Please try leaving the channel number empty after you select `add PSTH channel` menu. It will include all the event labels. You can select `preview` after adding the PSTH channel from .nev file to see what event labels are included.

**Comment by jamesjun** [comment]
I found a bug in the code that calculates the bar plot above and fixed it in v4.3.3.
