### ISSUE TITLE
in v4.3.3 error: Undefined function 'convertStringsToChars'

### ISSUE THREAD

**Issue by alejoe91** [jamesjun/ironclust#7]
Running ironclust from spiketoolkit on the example_dataset I get:

```
export_mda_: error exporting: /home/expipe/tmp/raw_geom.prm:
	Undefined function 'convertStringsToChars' for input arguments of type 'char'.
```

The error does not occur in version 4.3.2a

**Comment by jamesjun** [comment]
Implemented a fix for older Matlab versions (prior to R2017b). Note that recent Matlab versions (R2017b and later) will create string object when "..." is used. Otherwise it will create a vector of characters ('...').
